name: MoreBosses
main: net.ddns.vcccd.Main
version: 1.0
api-version: 1.20
commands:
   albert:
      description: Spawns Albert
      usage: /<command>
      permission: albert.spawn
   oswaldo:
      description: Spawns Oswaldo
      usage: /<command>
      permission: oswaldo.spawn
   tim:
      description: Spawns Tim
      usage: /<command>
      permission: tim.spawn
   albertremover:
      description: Gives you the Albert remover
      usage: /<command>
      permission: albertremover.give
   bigboy:
      description: Spawns Big Boy
      usage: /<command>
      permission: bigboy.spawn