name: MoreBosses
main: net.ddns.vcccd.Main
version: 1.2.2
api-version: 1.20
commands:
   albertremover:
      description: Gives you the Albert remover
      usage: /<command>
      permission: morebosses.albertremover
   morebosses:
      description: Opens the GUI
      usage: /<command>
      permission: morebosses.use
   removebars:
      description: Opens the GUI
      usage: /<command>
      permission: morebosses.removebars